version: '3.3'
services:
  db:
    image: postgres:10

  redis:
    image: redis

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "rails s"
    env_file:
      .env
    expose:
      - "3000"
    depends_on:
      - db
      - redis
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"

  nginx:
    build:
      context: services/nginx
    ports:
      - "80:80"
