version: '3.3'
services:
  db:
    image: postgres:10

  redis:
    image: redis

  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: sh -c "rails db:create db:migrate && rspec spec"
    env_file:
      - .env.test
    depends_on:
      - db
      - redis
