default: &default
  cloud_name: <%= CLOUDINARY_CLOUD_NAME %>
  api_key:    <%= CLOUDINARY_API_KEY %>
  api_secret: <%= CLOUDINARY_API_SECRET %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
