---
- hosts: all

  pre_tasks:
    - apt:
        update_cache: true
        name:
          - python3
          - python3-pip
      become: true

    - name: ensure group docker exists
      group:
        name: docker
      become: true

    - pip:
        name: docker
      become: true

  roles:
    - role: geerlingguy.docker
      become: true

  post_tasks:
    - user:
        name: "{{ catalog_with_telegram_bot_run_user }}"
        groups: docker
        append: true
      become: true

    - docker_network:
        name: "{{ catalog_with_telegram_bot_docker_network }}"
      tags: docker_network

  tasks:
    - name: create app dir
      file:
        path: "{{ catalog_with_telegram_bot_app_path }}"
        state: directory

    - template:
        src: environment.j2
        dest: "{{ catalog_with_telegram_bot_env_file }}"
      tags: env
